### ISSUE TITLE
New trackerlist

### ISSUE THREAD

**Issue by lighting9999** [shadowcovering/BitTorrentTrackersList#1]
[merged_merged_trackers_all_http.txt](https://github.com/user-attachments/files/17001687/merged_merged_trackers_all_http.txt)
新的tracker address请进行合并。数量太多了
[trackerlist.txt](https://github.com/user-attachments/files/17001686/trackerlist.txt)

**Comment by lighting9999** [comment]
这两个都是tracker地址文件

**Comment by shadowcovering** [comment]
ok, it's done~
如有其他issue，欢迎继续

**Comment by lighting9999** [comment]
ok



在 2024-09-20 23:45:22，"shadowcovering" ***@***.***> 写道：

ok, it's done~
如有其他issue，欢迎继续
